# ==============================================================================
# BAM Integrator - Example Script
# Full BAM data sets for NIS-2, DORA, etc. available via Knowledge-as-a-Service
# Visit: https://www.brain-media.de/kaas.html
# ==============================================================================

import json
import os

def load_json(filepath):
    """Lädt eine JSON-Datei sicher von der Festplatte."""
    if not os.path.exists(filepath):
        print(f"Fehler: Datei '{filepath}' nicht gefunden.")
        return None
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def validate_bam(data):
    """Prüft, ob das Objekt die notwendigen BAM-Ebenen enthält."""
    required = ["requirement", "risk", "control", "evidence"]
    for key in required:
        if key not in data:
            return False, f"Fehlendes BAM-Feld: {key}"
    return True, "Validierung erfolgreich: BAM-Objekt ist konform."

def generate_compliance_report(data):
    """Erzeugt eine Markdown-Ausgabe für Dokumentationszwecke (Wiki/Jira)."""
    report = f"""
# COMPLIANCE-TASK: {data.get('id', 'NEW-OBJECT')}
## Regulierung: {data.get('regulation', 'N/A')} - {data.get('article', 'N/A')}

### 1. ANFORDERUNG (Requirement)
{data['requirement']}

### 2. RISIKO-ASSESSMENT (Risk)
- **Einschätzung:** {data['risk'].get('impact', 'unbekannt')}
- **Risiko-Score:** {data['risk'].get('score', '0')}

### 3. MASSNAHME (Control)
- **Umsetzung:** {data['control'].get('measure')}
- **Priorität:** {data['control'].get('priority', 'normal')}

### 4. AUDIT-NACHWEIS (Evidence)
- **Typ:** {data['evidence'].get('type')}
- **Vorlage:** {data['evidence'].get('template', 'In KaaS-Abo enthalten')}

---
*Generated by Brain-Media BAM-Integrator*
"""
    return report

def main():
    print("--- Brain-Media.de | BAM Integrator Start ---\n")
    
    # Pfad zur Beispiel-Datei (bam-example.json im selben Verzeichnis)
    data_file = 'bam-example.json'
    
    # Beispiel-Daten laden
    bam_data = load_json(data_file)
    
    if bam_data:
        # 1. Validierung
        is_valid, msg = validate_bam(bam_data)
        print(f"[*] {msg}")
        
        if is_valid:
            # 2. Transformation / Reporting
            print("[*] Erzeuge Compliance-Report...")
            markdown_output = generate_compliance_report(bam_data)
            
            # Ausgabe in der Konsole (oder in Datei schreiben)
            print("-" * 40)
            print(markdown_output)
            print("-" * 40)
            
            print("\nERGEBNIS: Das BAM-Objekt wurde erfolgreich prozessiert.")
            print("HINWEIS: Für den automatisierten API-Export in GRC-Tools (ServiceNow, Jira) kontaktieren Sie uns.")
    
    print("\nBesuchen Sie https://www.brain-media.de/kaas.html für den vollständigen Datensatz.")

if __name__ == "__main__":
    main()